[project]
name = "optuna-sample"
version = "0.1.0"
description = "Sample code to optimize hyperparameters with Optuna"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "optuna>=4.1.0",
    "scipy>=1.14.1",
]
